Add reminder about ignoring *.backup files via .npmignore
roydukkey/clean-package pull request #15
Opened 2021-11-10 07:18 UTC by Snaptags

There should be a reminder about adding an entry to `.npmignore`. Otherwise people might add the backup file to their packed packages and probably won't even notice it.

2021-11-11 03:48 UTC, roydukkey requested changes
How do these changes look?

2021-11-11 03:48 UTC, roydukkey commented on README.md
> +Edit your `.npmignore` file (or add one) and be sure to ignore the backup file. For example:
```suggestion
When the "prepack" script executes, a backup of the original `package.json` will be created. Ensure this file doesn't make it into your release package.

One way to accomplish this is to add the following to your `.npmignore` file:

```

2021-11-11 03:48 UTC, roydukkey commented on README.md
> +# Build Artifacts
```suggestion
```

2021-11-11 03:48 UTC, roydukkey commented on README.md
> +```text
```suggestion
```ignore
```

2021-11-14 21:34 UTC, Snaptags commented
Thanks for reviewing! I like your suggested changes and applied them.

2021-11-15 16:05 UTC, merged

2021-11-15 16:05 UTC, roydukkey commented
Thanks!